// Migration file placeholder
// In production, this would be generated by: dotnet ef migrations add InitialCreate
// This file is created for reference and can be regenerated using EF Core migrations

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FixitBackend.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Note: This is a placeholder migration file
            // To generate proper migrations, run:
            // dotnet ef migrations add InitialCreate -o Infrastructure/Migrations
            // This will create the proper Up/Down methods based on your DbContext
            
            // The FixItDbContext and SeedData will handle schema creation and seeding
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Down migrations would be auto-generated
        }
    }
}
