// Migration model snapshot
// This is auto-generated by EF Core migrations
// To regenerate: dotnet ef migrations add InitialCreate -o Infrastructure/Migrations

using FixitBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace FixitBackend.Infrastructure.Migrations
{
    [DbContext(typeof(FixItDbContext))]
    partial class FixItDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // This is a placeholder
            // The actual model snapshot will be generated by EF Core when you run:
            // dotnet ef migrations add InitialCreate
        }
    }
}
